import { Recipe } from "./types";

export const INITIAL_RECIPES: Partial<Recipe>[] = [
    // WANT TO COOK
    { title: "Oxtail", category: "Want to Cook", image_url: "" },
    { title: "Filipino Pork Adobo", category: "Want to Cook", link: "https://www.recipetineats.com/filipino-pork-adobo/", image_url: "" },
    { title: "Vindaloo", category: "Want to Cook", image_url: "" },
    { title: "Rogen Josh", category: "Want to Cook", image_url: "" },
    { title: "Japchae - Korean Noodles", category: "Want to Cook", image_url: "" },
    { title: "Tom Yum Soup", category: "Want to Cook", image_url: "" },
    { title: "Pork and fennel sausage roll", category: "Want to Cook", image_url: "" },

    // MAINS
    { title: "Beef ragu", category: "Mains", image_url: "" },
    { title: "Dan Dan Noodles", category: "Mains", image_url: "" },
    { title: "Pad See Ew", category: "Mains", image_url: "" },
    { title: "Couscous Salad", category: "Mains", image_url: "" },
    { title: "Okonomiyaki", category: "Mains", image_url: "" },
    { title: "Chicken Schnitzel", category: "Mains", image_url: "" },
    { title: "Beef Stew + Mash", category: "Mains", image_url: "" },
    { title: "Fried Chicken Burger", category: "Mains", image_url: "" },
    { title: "Smash Burger", category: "Mains", image_url: "" },
    { title: "Rice Paper Rolls", category: "Mains", image_url: "" },
    { title: "Fish Green Curry", category: "Mains", image_url: "" },
    { title: "Beef Massaman", category: "Mains", image_url: "" },
    { title: "Chicken & Pumpkin Red Curry", category: "Mains", image_url: "" },
    { title: "Lemongrass Chicken Vermicelli", category: "Mains", image_url: "" },
    { title: "Chicken Gyros", category: "Mains", image_url: "" },
    { title: "Tacos (Chicken/Beef/Pork)", category: "Mains", image_url: "" },
    { title: "Burrito Bowl", category: "Mains", image_url: "" },
    { title: "Salmon Poke Bowl", category: "Mains", image_url: "" },
    { title: "Miso Eggplant Bowl", category: "Mains", image_url: "" },
    { title: "Chicken and Leek Pie", category: "Mains", image_url: "" },
    { title: "Bibimbap", category: "Mains", image_url: "" },
    { title: "Beef & Green Bean Stir Fry", category: "Mains", image_url: "" },
    { title: "Chorizo Chicken Creamy Pasta", category: "Mains", image_url: "" },
    { title: "Pumpkin & Burnt Butter Sage Pasta", category: "Mains", image_url: "" },
    { title: "Pumpkin Puree & Sausage Pasta", category: "Mains", image_url: "" },
    { title: "Butterfly Prawn w/ French Butter Sauce", category: "Mains", image_url: "" },
    { title: "Roasted Butterfly Chicken + Butter beans", category: "Mains", image_url: "" },
    { title: "Chicken Pot Pie", category: "Mains", image_url: "" },
    { title: "Lamb and Rosemary Pie", category: "Mains", image_url: "" },
    { title: "Beef and Mushroom Pie (RTE)", category: "Mains", image_url: "" },
    { title: "Chicken Biryani", category: "Mains", image_url: "" },
    { title: "Steak & Chimichurri", category: "Mains", image_url: "" },
    { title: "Thai Beef Salad", category: "Mains", image_url: "" },
    { title: "Fried Rice", category: "Mains", image_url: "" },
    { title: "One Pan Chicken Feta Bean Bake", category: "Mains", image_url: "" },
    { title: "Bao Buns", category: "Mains", image_url: "" },
    { title: "Homemade Pizza", category: "Mains", image_url: "" },
    { title: "Moroccan Eggplant & Pumpkin Salad", category: "Mains", image_url: "" },
    { title: "Falafel w/ Pita & Hummus", category: "Mains", image_url: "" },
    { title: "Moroccan Chicken Chickpea Bake", category: "Mains", image_url: "" },
    { title: "Pasta ALLA Norma", category: "Mains", image_url: "" },

    // SOUP
    { title: "Red Curry Pumpkin Soup", category: "Soup", image_url: "" },
    { title: "Chicken Pho", category: "Soup", image_url: "" },
    { title: "Creamy Tuscan Chicken Soup", category: "Soup", link: "https://www.recipetineats.com/creamy-tuscan-chicken-soup/", image_url: "" },
    { title: "Avgolemono Greek Soup", category: "Soup", image_url: "" },
    { title: "Minestrone", category: "Soup", image_url: "" },
    { title: "Green Goddess Soup", category: "Soup", image_url: "" },
    { title: "Pea and Ham Soup", category: "Soup", image_url: "" },
    { title: "Chinese Noodle Soup", category: "Soup", image_url: "" },
    { title: "Wonton Noodle Soup", category: "Soup", image_url: "" },
    { title: "Laksa (RTE)", category: "Soup", image_url: "" },

    // SNACKS
    { title: "Edamame", category: "Snacks", image_url: "" },
    { title: "Bruschetta", category: "Snacks", image_url: "" },
    { title: "Coconut Chilli Kingfish Sashimi", category: "Snacks", image_url: "" },
    { title: "Dumplings", category: "Snacks", image_url: "" },
    { title: "Asian Greens", category: "Snacks", image_url: "" },
    { title: "Korean Chicken Wings", category: "Snacks", image_url: "" },
    { title: "Pumpkin Pine Nut Yogurt", category: "Snacks", image_url: "" },

    // BREAKFAST
    { title: "Salmon Cream Cheese Bagel", category: "Breakfast", image_url: "" },
    { title: "Turkish Eggs", category: "Breakfast", image_url: "" },
    { title: "Chilli Crisp Sandwich", category: "Breakfast", image_url: "" },
    { title: "Shakshuka", category: "Breakfast", image_url: "" },

    // SWEETS
    { title: "Carrot Cake", category: "Sweets", image_url: "" },
    { title: "Peanut Butter Cups", category: "Sweets", image_url: "" },
    { title: "Lemon Poppy Seed Cake", category: "Sweets", image_url: "" },
    { title: "Pumpkin Cheesecake", category: "Sweets", image_url: "" },
    { title: "Banana Bread", category: "Sweets", image_url: "" },
    { title: "Sticky Date Pudding", category: "Sweets", image_url: "" },
    { title: "Lemon Yoghurt Blueberry Cake", category: "Sweets", image_url: "" },
    { title: "Blueberry Crumble", category: "Sweets", image_url: "" },
    { title: "Tiramisu", category: "Sweets", link: "https://www.gourmettraveller.com.au/recipe/dessert/tiramisu-11058/", image_url: "" },
    { title: "Limoncello Tiramisu", category: "Sweets", image_url: "" },
    { title: "Coconut Cake", category: "Sweets", link: "https://sallysbakingaddiction.com/coconut-cake/", image_url: "" },
];
