import { Recipe } from "./types";

const getImg = (query: string) => `https://image.pollinations.ai/prompt/delicious%20${encodeURIComponent(query)}%20plated%20meal%20professional%20food%20photography%20lighting?nologo=true&width=800&height=600&seed=${Math.floor(Math.random() * 1000)}`;

export const INITIAL_RECIPES: Partial<Recipe>[] = [
    // WANT TO COOK
    { title: "Oxtail", category: "Want to Cook", image_url: getImg("Oxtail stew rich sauce") },
    { title: "Filipino Pork Adobo", category: "Want to Cook", link: "https://www.recipetineats.com/filipino-pork-adobo/", image_url: getImg("Filipino Pork Adobo") },
    { title: "Vindaloo", category: "Want to Cook", image_url: getImg("Lamb Vindaloo curry") },
    { title: "Rogan Josh", category: "Want to Cook", image_url: getImg("Rogan Josh curry") },
    { title: "Japchae (Korean Noodles)", category: "Want to Cook", image_url: getImg("Japchae korean glass noodles") },
    { title: "Tom Yum Soup", category: "Want to Cook", image_url: getImg("Tom Yum Soup prawn") },
    { title: "Pork and Fennel Sausage Roll", category: "Want to Cook", image_url: getImg("Pork and fennel sausage roll pastry") },

    // MAINS
    { title: "Beef Ragu", category: "Mains", image_url: getImg("Beef Ragu pasta") },
    { title: "Dan Dan Noodles", category: "Mains", image_url: getImg("Dan Dan Noodles spicy") },
    { title: "Pad See Ew", category: "Mains", image_url: getImg("Pad See Ew thai noodles") },
    { title: "Couscous Salad", category: "Mains", image_url: getImg("Couscous Salad fresh") },
    { title: "Okonomiyaki", category: "Mains", image_url: getImg("Okonomiyaki japanese pancake") },
    { title: "Chicken Schnitzel", category: "Mains", image_url: getImg("Chicken Schnitzel golden") },
    { title: "Beef Stew + Mash", category: "Mains", image_url: getImg("Beef Stew and Mashed Potato") },
    { title: "Fried Chicken Burger", category: "Mains", image_url: getImg("Fried Chicken Burger") },
    { title: "Smash Burger", category: "Mains", image_url: getImg("Smash Burger cheese") },
    { title: "Rice Paper Rolls", category: "Mains", image_url: getImg("Fresh Rice Paper Rolls") },
    { title: "Fish Green Curry", category: "Mains", image_url: getImg("Thai Green Fish Curry") },
    { title: "Beef Massaman", category: "Mains", image_url: getImg("Beef Massaman Curry") },
    { title: "Chicken & Pumpkin Red Curry", category: "Mains", image_url: getImg("Chicken Pumpkin Red Curry") },
    { title: "Lemongrass Chicken Vermicelli", category: "Mains", image_url: getImg("Lemongrass Chicken Vermicelli Salad") },
    { title: "Chicken Gyros", category: "Mains", image_url: getImg("Chicken Gyros wrap") },
    { title: "Tacos (Chicken/Beef/Pork)", category: "Mains", image_url: getImg("Mexican Tacos feast") },
    { title: "Burrito Bowl", category: "Mains", image_url: getImg("Burrito Bowl fresh") },
    { title: "Salmon Poke Bowl", category: "Mains", image_url: getImg("Salmon Poke Bowl avocado") },
    { title: "Miso Eggplant Bowl", category: "Mains", image_url: getImg("Miso Eggplant Rice Bowl") },
    { title: "Chicken and Leek Pie", category: "Mains", image_url: getImg("Chicken and Leek Pie") },
    { title: "Bibimbap", category: "Mains", image_url: getImg("Korean Bibimbap") },
    { title: "Beef & Green Bean Stir Fry", category: "Mains", image_url: getImg("Beef and Green Bean Stir Fry") },
    { title: "Chorizo Chicken Creamy Pasta", category: "Mains", image_url: getImg("Creamy Chorizo Chicken Pasta") },
    { title: "Pumpkin & Burnt Butter Sage Pasta", category: "Mains", image_url: getImg("Pumpkin Burnt Butter Sage Pasta") },
    { title: "Pumpkin Puree & Sausage Pasta", category: "Mains", image_url: getImg("Pumpkin Puree Sausage Pasta") },
    { title: "Butterfly Prawn w/ French Butter Sauce", category: "Mains", image_url: getImg("Butterfly Prawns Butter Sauce") },
    { title: "Roasted Butterfly Chicken + Butter Beans", category: "Mains", image_url: getImg("Roasted Butterfly Chicken") },
    { title: "Chicken Pot Pie", category: "Mains", image_url: getImg("Chicken Pot Pie golden") },
    { title: "Lamb and Rosemary Pie", category: "Mains", image_url: getImg("Lamb and Rosemary Pie") },
    { title: "Beef and Mushroom Pie", category: "Mains", image_url: getImg("Beef and Mushroom Pie") },
    { title: "Chicken Biryani", category: "Mains", image_url: getImg("Chicken Biryani pot") },
    { title: "Steak & Chimichurri", category: "Mains", image_url: getImg("Steak Chimichurri Potatoes") },
    { title: "Thai Beef Salad", category: "Mains", image_url: getImg("Thai Beef Salad fresh") },
    { title: "Fried Rice", category: "Mains", image_url: getImg("Chinese Fried Rice") },
    { title: "One Pan Chicken Feta Bean Bake", category: "Mains", image_url: getImg("Chicken Feta Butter Bean Bake") },
    { title: "Bao Buns", category: "Mains", image_url: getImg("Pork Bao Buns") },
    { title: "Homemade Pizza", category: "Mains", image_url: getImg("Homemade Pizza rustic") },
    { title: "Moroccan Eggplant & Pumpkin Salad", category: "Mains", image_url: getImg("Moroccan Eggplant Pumpkin Salad") },
    { title: "Falafel w/ Pita & Hummus", category: "Mains", image_url: getImg("Falafel Pita Hummus Plate") },
    { title: "Moroccan Chicken Chickpea Bake", category: "Mains", image_url: getImg("Moroccan Chicken Chickpea Bake") },
    { title: "Pasta alla Norma", category: "Mains", image_url: getImg("Pasta alla Norma eggplant") },

    // SOUP
    { title: "Red Curry Pumpkin Soup", category: "Soup", image_url: getImg("Red Curry Pumpkin Soup") },
    { title: "Chicken Pho", category: "Soup", image_url: getImg("Chicken Pho Soup") },
    { title: "Creamy Tuscan Chicken Soup", category: "Soup", link: "https://www.recipetineats.com/creamy-tuscan-chicken-soup/", image_url: getImg("Creamy Tuscan Chicken Soup") },
    { title: "Avgolemono Greek Soup", category: "Soup", image_url: getImg("Avgolemono Soup") },
    { title: "Minestrone", category: "Soup", image_url: getImg("Minestrone Soup") },
    { title: "Green Goddess Soup", category: "Soup", image_url: getImg("Green Goddess Soup") },
    { title: "Pea and Ham Soup", category: "Soup", image_url: getImg("Pea and Ham Soup") },
    { title: "Chinese Noodle Soup", category: "Soup", image_url: getImg("Chinese Noodle Soup") },
    { title: "Wonton Noodle Soup", category: "Soup", image_url: getImg("Wonton Noodle Soup") },
    { title: "Laksa", category: "Soup", image_url: getImg("Laksa Noodle Soup") },

    // SNACKS
    { title: "Edamame", category: "Snacks", image_url: getImg("Edamame beans") },
    { title: "Bruschetta", category: "Snacks", image_url: getImg("Tomato Bruschetta") },
    { title: "Coconut Chilli Kingfish Sashimi", category: "Snacks", image_url: getImg("Kingfish Sashimi") },
    { title: "Dumplings", category: "Snacks", image_url: getImg("Steamed Dumplings") },
    { title: "Asian Greens", category: "Snacks", image_url: getImg("Stir fry Asian Greens") },
    { title: "Korean Chicken Wings", category: "Snacks", image_url: getImg("Korean Fried Chicken Wings") },
    { title: "Pumpkin Pine Nut Yogurt", category: "Snacks", image_url: getImg("Pumpkin Pine Nut Dip") },

    // BREAKFAST
    { title: "Salmon Cream Cheese Bagel", category: "Breakfast", image_url: getImg("Salmon Cream Cheese Bagel") },
    { title: "Turkish Eggs", category: "Breakfast", image_url: getImg("Turkish Eggs Cilbir") },
    { title: "Chilli Crisp Sandwich", category: "Breakfast", image_url: getImg("Chilli Crisp Egg Sandwich") },
    { title: "Shakshuka", category: "Breakfast", image_url: getImg("Shakshuka eggs tomato") },

    // SWEETS
    { title: "Carrot Cake", category: "Sweets", image_url: getImg("Carrot Cake slice") },
    { title: "Peanut Butter Cups", category: "Sweets", image_url: getImg("Homemade Peanut Butter Cups") },
    { title: "Lemon Poppy Seed Cake", category: "Sweets", image_url: getImg("Lemon Poppy Seed Cake") },
    { title: "Pumpkin Cheesecake", category: "Sweets", image_url: getImg("Pumpkin Cheesecake") },
    { title: "Banana Bread", category: "Sweets", image_url: getImg("Banana Bread slice") },
    { title: "Sticky Date Pudding", category: "Sweets", image_url: getImg("Sticky Date Pudding") },
    { title: "Lemon Yoghurt Blueberry Cake", category: "Sweets", image_url: getImg("Lemon Blueberry Cake") },
    { title: "Blueberry Crumble", category: "Sweets", image_url: getImg("Blueberry Crumble dessert") },
    { title: "Tiramisu", category: "Sweets", link: "https://www.gourmettraveller.com.au/recipe/dessert/tiramisu-11058/", image_url: getImg("Tiramisu classic") },
    { title: "Limoncello Tiramisu", category: "Sweets", image_url: getImg("Lemon Tiramisu") },
    { title: "Coconut Cake", category: "Sweets", link: "https://sallysbakingaddiction.com/coconut-cake/", image_url: getImg("Coconut Cake slice") },
];
